### ISSUE TITLE
Framework review 1.0

### ISSUE THREAD

**Issue by ooow** [Guseyn/page#275]
The framework is really good designed and well implemented, also the idea is interesting. I've tried and it works totally fine, has a lot of features and looks like a good tool to use.

Here are a few technical suggestions: 

- [x] Improve the fraewmork to create project with next command: `page create <project-name>`
- [x] Add url to open after `page br`
- [ ] Fix all typos (with `the`) in Readme
- [x] Fix description (do not forget about 'page br' command)
- [x] Fix favicon missing error (add some standard)
- [x] Remove useless css in project (like static/css/page.css/button)
- [x] Rename github.svg.png - choose one .png or .svg
- [x] Remove old logo.png (static/image/logo.png)
- [x] Finish or remove static/html folder - it makes no sense right now
- [x] Clean up all project tempaltes (for example in tempaltes/page.html usless id="page")
- [x] Remove extra empty lines in each file (for example in .gitignore - 2 extra empty lines in the end of the file)
- [x] Remove txt folder - it seems a bit strange. You can user logo.txt as an optional feature (page crate --with-logo or -wl)

Here are a few usability suggestions: 

- [x] Animate some of the elements on the default template. (for example, rotate the logo. it makes the framework more user-friendly)
- [x] Do welcome the user - write some greeting
- [x] Add to the documentation information about which directories can be modified by a user and which is forbidden (Also, I recommend to collect all forbidden stuff into one place where a user should not look)
- [x] Consider updating the framework logotype (you can do better)
- [x] Simplify the framework description - make it easy to read. I suggest to use the next structure: 

> 1. Short framework description.
> 2. How to use manual (install and start with gif examples).
> 3. Show and explain the project structure.
> 4. All other stuff.

Thanks for your job
👍

**Comment by Guseyn** [comment]
@ooow  Thanks bro, I will try to improve the project!
